### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by anoduck** [kalinochkind/imgsrc-grabber#3]
Everytime I run this I receive the error `IndexError: list index out of range`

**Comment by gophra** [comment]
Can you provide more information?

**Comment by anoduck** [comment]
That was over four years ago, and I do not receive the same error. Now, the error is:

```bash
https://imgsrc.ru/kos16/a1458963.html
First photo: https://imgsrc.ru/kos16/a1458963.html
Visiting https://imgsrc.ru/kos16/a1458963.html
Traceback (most recent call last):
  File "/home/imgsrc-grabber/main.py", line 274, in <module>
    main()
  File "/home/imgsrc-grabber/main.py", line 270, in main
    parser.get_photos_from_url(url)
  File "/home/imgsrc-grabber/main.py", line 234, in get_photos_from_url
    self.get_photos(url)
  File "/home/imgsrc-grabber/main.py", line 174, in get_photos
    self.download_photo(self.get_photo_url(d.body.decode('utf-8')), workdir)
  File "/home/imgsrc-grabber/main.py", line 209, in get_photo_url
    answer = self.photo_result_re.search(body).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

The problematic function appears to be `get_photo_url` in the class `ImgsrcParcer`:

```python
    def get_photo_url(self, body):
        js = [i.rstrip(',') for i in sum([x.splitlines() for x in self.photo_js_re.findall(body)], [])]
        js = sum([i.split(', ') for i in js], [])
        answer = self.photo_result_re.search(body).group(1)
        variables = {'_url': self.photo_re.search(body).group(1)}
        for cmd in js:
            if 'new Image(' in cmd:
                continue
            name, val = cmd.split('=')
            result = exec_js(val, variables)
            variables[name] = result
        return eval_js(answer.replace('-', '+-').split('+'), variables)
```
